"""Build the outcome-independent Journal J1 semantic scenario frame (no prompts or APIs)."""
from __future__ import annotations
import argparse,csv,hashlib,json
from collections import Counter
from pathlib import Path
from .decision_point_confirmatory_scenarios_v1_0_0 import SCENARIOS as ICAART_INPUT_SCENARIOS
from .journal_j1_inference_sampling_v0_2_1 import SELECTION_SEED,SELECTION_SEED_LITERAL,select_candidates
ARCHETYPES={
 'resource_location':('RL','location','active_resource_location','other_resource_location'),
 'tool_placement':('TP','location','required_tool_location','other_tool_location'),
 'rendezvous_destination':('RD','destination','active_rendezvous_destination','other_movement_destination'),
 'delivery_destination':('DD','destination','active_payload_destination','other_payload_destination'),
 'hazard_assignment':('HA','sector','active_hazard_sector','other_hazard_sector'),
 'maintenance_target':('MT','component','active_maintenance_component','other_maintenance_component')}
DIFFICULTIES={'direct':('DIR',1),'irrelevant_distractor':('DIS',1),'compositional':('COM',2)}
PROHIBITED_RENDERABLE=('relevant','irrelevant','m_r','m_i','gold','should_communicate','necessary_correction','unnecessary_correction','stale','current','heldout alpha','heldout omega')
ROOT=Path(__file__).resolve().parents[1]
OUTPUTS=('journal_j1_confirmatory_candidate_frame_v0_3_0.json','journal_j1_confirmatory_selection_v0_3_0.json','journal_j1_development_scenarios_v0_3_0.json','journal_j1_scenario_semantic_audit_v0_3_0.json','journal_j1_scenario_semantic_audit_v0_3_0.csv')
def canonical(value):return json.dumps(value,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def digest(value):return hashlib.sha256(canonical(value)).hexdigest()
def cells(q_true,q_false,r_true,r_false,world_hash,actions):
 return [{'F':f,'M_R':mr,'M_I':mi,'partner_q_value':q_false if mr else q_true,'partner_r_value':r_false if mi else r_true,'gold_action_class':'communicate' if mr else 'progress','objective_world_sha256':world_hash,'available_action_ids':actions} for f in ('R','B') for mr in (0,1) for mi in (0,1)]
def make_variant(namespace,archetype,difficulty,ordinal):
 archcode,value_type,qkind,rkind=ARCHETYPES[archetype];diffcode,depth=DIFFICULTIES[difficulty];prefix='J1C' if namespace=='confirmatory_candidate' else 'J1D';variant_id=f'{prefix}-{archcode}-{diffcode}-{ordinal:02d}';ns='j1c' if prefix=='J1C' else 'j1d';stem=f'{ns}_{archcode.lower()}_{diffcode.lower()}_{ordinal:02d}'
 q_true=f'{stem}_{value_type}_q_a';q_false=f'{stem}_{value_type}_q_b';r_true=f'{stem}_{value_type}_r_a';r_false=f'{stem}_{value_type}_r_b';active=f'{stem}_active_task';partner=f'{stem}_partner';focal=f'{stem}_focal_agent'
 correction=f'{stem}_correction_action';progress=f'{stem}_progress_action';actions=[correction,progress]
 world={'active_task_id':active,'q_truth':q_true,'r_truth':r_true,'focal_agent_knowledge':[q_true,r_true],'partner_next_step_rule':{'target_source':'q_proposition','active_task_id':active},'causal_task_rules':[{'if_partner_q_matches_truth':'progress','if_partner_q_differs_from_truth':'communicate'}],'difficulty_structure':{'difficulty':difficulty,'parallel_relation_depth':depth}}
 if depth==2:world['parallel_relation_chains']=[{'subject':f'{stem}_active_item','via':f'{stem}_active_category','value':q_true},{'subject':f'{stem}_other_item','via':f'{stem}_other_category','value':r_true}]
 static=[] if difficulty=='direct' else ([{'fact_id':f'{stem}_ambient_schedule','value':f'{stem}_schedule_slot'}] if difficulty=='irrelevant_distractor' else [{'fact_id':f'{stem}_category_map','value':f'{stem}_mapping'}])
 world_hash=digest(world)
 record={'variant_id':variant_id,'namespace':namespace,'archetype':archetype,'difficulty':difficulty,'candidate_ordinal_in_cell':ordinal,'active_task_id':active,'focal_agent_id':focal,'partner_id':partner,'objective_world_facts':world,'q_proposition_id':f'{stem}_{qkind}','q_semantic_type':value_type,'q_true':q_true,'q_false':q_false,'q_causal_dependency':{'partner_next_active_step_target_source':'q_proposition_id','wrong_value_without_correction_conflicts_with_active_task':True,'dependency_edges':[f'{stem}_{qkind}->partner_next_active_step']},'q_relation_depth':depth,'r_proposition_id':f'{stem}_{rkind}','r_semantic_type':value_type,'r_true':r_true,'r_false':r_false,'r_noncausal_context':{'associated_context_id':f'{stem}_nonactive_context','dependency_edges_to_partner_next_active_step':[],'changing_value_changes_gold_policy':False},'r_relation_depth':depth,'static_context_facts':static,'correction_action_id':correction,'progress_action_id':progress,'correction_content_semantic_value':q_true,'available_action_ids':actions,'gold_policy_rule':{'input_factor':'M_R','communicate_value':1,'progress_value':0},'future_renderable_facts':{'active_task_id':active,'objective_values':[q_true,r_true],'represented_value_domain':[q_true,q_false,r_true,r_false],'static_context_facts':static},'internal_metadata_fields':['F','M_R','M_I','gold_action_class','difficulty','q_causal_dependency','r_noncausal_context']}
 record['counterfactual_cells']=cells(q_true,q_false,r_true,r_false,world_hash,actions);signature_content={k:v for k,v in record.items() if k not in ('variant_id','namespace','candidate_ordinal_in_cell','counterfactual_cells')};record['semantic_signature_sha256']=digest(signature_content);return record
def candidate_records():return [make_variant('confirmatory_candidate',a,d,i) for a in ARCHETYPES for d in DIFFICULTIES for i in range(1,21)]
def development_records():return [make_variant('development',a,d,1) for a in ARCHETYPES for d in DIFFICULTIES]
def variant_entities(record):
 values={record[k] for k in ('active_task_id','focal_agent_id','partner_id','q_true','q_false','r_true','r_false','correction_action_id','progress_action_id')};return values
def audit_variant(r):
 cs=r['counterfactual_cells'];combos={(c['F'],c['M_R'],c['M_I']) for c in cs};actions={tuple(c['available_action_ids']) for c in cs};world={c['objective_world_sha256'] for c in cs}
 by={(c['F'],c['M_R'],c['M_I']):c for c in cs};q_ok=all(c['partner_q_value']==(r['q_false'] if c['M_R'] else r['q_true']) for c in cs);r_ok=all(c['partner_r_value']==(r['r_false'] if c['M_I'] else r['r_true']) for c in cs);gold=all(c['gold_action_class']==('communicate' if c['M_R'] else 'progress') for c in cs)
 framing=all(by['R',mr,mi]['gold_action_class']==by['B',mr,mi]['gold_action_class'] and by['R',mr,mi]['partner_q_value']==by['B',mr,mi]['partner_q_value'] and by['R',mr,mi]['partner_r_value']==by['B',mr,mi]['partner_r_value'] for mr in (0,1) for mi in (0,1));irrelevant=all(by[f,mr,0]['gold_action_class']==by[f,mr,1]['gold_action_class'] for f in ('R','B') for mr in (0,1));rendered=canonical(r['future_renderable_facts']).decode().lower()
 checks={'eight_cells':len(cs)==8 and len(combos)==8,'world_truth_fixed':len(world)==1,'action_sets_fixed':len(actions)==1 and next(iter(actions))==tuple(r['available_action_ids']),'q_mismatch_only_depends_on_mr':q_ok,'r_mismatch_only_depends_on_mi':r_ok,'gold_depends_only_on_mr':gold,'framing_gold_invariant':framing,'irrelevant_gold_invariant':irrelevant,'semantic_types_matched':r['q_semantic_type']==r['r_semantic_type'],'relation_depths_matched':r['q_relation_depth']==r['r_relation_depth'],'compositional_depth_two':r['difficulty']!='compositional' or r['q_relation_depth']==r['r_relation_depth']==2,'other_depth_one':r['difficulty']=='compositional' or r['q_relation_depth']==r['r_relation_depth']==1,'false_values_distinct_from_true':r['q_true']!=r['q_false'] and r['r_true']!=r['r_false'],'all_four_values_distinct':len({r['q_true'],r['q_false'],r['r_true'],r['r_false']})==4,'q_structurally_causal':r['q_causal_dependency']['wrong_value_without_correction_conflicts_with_active_task'] and bool(r['q_causal_dependency']['dependency_edges']),'r_structurally_noncausal':not r['r_noncausal_context']['dependency_edges_to_partner_next_active_step'] and not r['r_noncausal_context']['changing_value_changes_gold_policy'],'distractor_static_context':r['difficulty']!='irrelevant_distractor' or bool(r['static_context_facts']),'no_renderable_leakage':not any(x in rendered for x in PROHIBITED_RENDERABLE)};return checks
def aggregate_audit(candidates,development,selected=None,frame_hash=None):
 rows=candidates+development;individual=[audit_variant(r) for r in rows];candidate_ids={r['variant_id'] for r in candidates};development_ids={r['variant_id'] for r in development};candidate_entities=set().union(*(variant_entities(r) for r in candidates));development_entities=set().union(*(variant_entities(r) for r in development));old_entities={x for s in ICAART_INPUT_SCENARIOS for x in (s.entity_a,s.entity_b)};old_ids={s.variant_id for s in ICAART_INPUT_SCENARIOS};selected_ids=set(selected or ());cell=lambda r:f"{r['archetype']}|{r['difficulty']}"
 audit={'candidate_count':len(candidates),'development_count':len(development),'candidate_cell_counts':dict(Counter(cell(r) for r in candidates)),'selected_cell_counts':dict(Counter(cell(r) for r in candidates if r['variant_id'] in selected_ids)),'unselected_cell_counts':dict(Counter(cell(r) for r in candidates if r['variant_id'] not in selected_ids)),'candidate_archetype_counts':dict(Counter(r['archetype'] for r in candidates)),'candidate_difficulty_counts':dict(Counter(r['difficulty'] for r in candidates)),'selected_archetype_counts':dict(Counter(r['archetype'] for r in candidates if r['variant_id'] in selected_ids)),'selected_difficulty_counts':dict(Counter(r['difficulty'] for r in candidates if r['variant_id'] in selected_ids)),'candidate_unique_ids':len(candidate_ids),'candidate_unique_semantic_hashes':len({r['semantic_signature_sha256'] for r in candidates}),'development_unique_ids':len(development_ids),'development_unique_semantic_hashes':len({r['semantic_signature_sha256'] for r in development}),'development_candidate_id_overlap':len(candidate_ids&development_ids),'development_candidate_entity_overlap':len(candidate_entities&development_entities),'development_candidate_semantic_overlap':len({r['semantic_signature_sha256'] for r in candidates}&{r['semantic_signature_sha256'] for r in development}),'old_icaart_exact_entity_overlap':len((candidate_entities|development_entities)&old_entities),'old_icaart_exact_variant_id_overlap':len((candidate_ids|development_ids)&old_ids),'legacy_heldout_pattern_count':sum(any(x in entity.lower() for x in ('heldout alpha','heldout omega')) for entity in candidate_entities|development_entities)}
 aggregate_names={'eight_cells':'all_variants_eight_cells','world_truth_fixed':'all_world_truth_fixed','action_sets_fixed':'all_action_sets_fixed','q_mismatch_only_depends_on_mr':'all_q_mismatch_only_depends_on_mr','r_mismatch_only_depends_on_mi':'all_r_mismatch_only_depends_on_mi','gold_depends_only_on_mr':'all_gold_depends_only_on_mr','framing_gold_invariant':'all_framing_gold_invariant','irrelevant_gold_invariant':'all_irrelevant_gold_invariant','semantic_types_matched':'all_semantic_types_matched','relation_depths_matched':'all_relation_depths_matched','compositional_depth_two':'all_compositional_depth_two','other_depth_one':'all_other_depth_one','false_values_distinct_from_true':'all_false_values_distinct_from_true','all_four_values_distinct':'all_four_values_distinct','q_structurally_causal':'all_q_structurally_causal','r_structurally_noncausal':'all_r_structurally_noncausal','distractor_static_context':'all_distractor_static_context','no_renderable_leakage':'all_no_renderable_leakage'}
 for key,name in aggregate_names.items():audit[name]=all(row[key] for row in individual)
 audit['gold_communicate_probability_given_mr1']=1.0 if audit['all_gold_depends_only_on_mr'] else None;audit['gold_communicate_probability_given_mr0']=0.0 if audit['all_gold_depends_only_on_mr'] else None
 mandatory=[audit['candidate_count']==360,audit['development_count']==18,set(audit['candidate_cell_counts'].values())=={20},audit['candidate_unique_ids']==audit['candidate_unique_semantic_hashes']==360,audit['development_unique_ids']==audit['development_unique_semantic_hashes']==18,audit['development_candidate_id_overlap']==audit['development_candidate_entity_overlap']==audit['development_candidate_semantic_overlap']==0,audit['old_icaart_exact_entity_overlap']==audit['old_icaart_exact_variant_id_overlap']==audit['legacy_heldout_pattern_count']==0,all(all(row.values()) for row in individual)]
 audit['preselection_passed']=all(mandatory);audit['all_selection_from_passed_frame']=audit['preselection_passed'] and (not selected_ids or selected_ids<=candidate_ids);audit['candidate_frame_hash_verified']=frame_hash==digest(candidates) if frame_hash else False;audit['passed']=audit['preselection_passed'] and audit['all_selection_from_passed_frame'] and audit['candidate_frame_hash_verified'];return audit
def build_artifacts(candidates=None,development=None):
 candidates=candidate_records() if candidates is None else candidates;development=development_records() if development is None else development
 grouped={(a,d):[r for r in candidates if r['archetype']==a and r['difficulty']==d] for a in ARCHETYPES for d in DIFFICULTIES}
 if any([r['variant_id'] for r in records]!=sorted(r['variant_id'] for r in records) for records in grouped.values()):raise RuntimeError('candidate order not canonical')
 pre=audit_variant(candidates[0]) if candidates else {};preaudit=aggregate_audit(candidates,development)
 if not pre or not preaudit['preselection_passed']:raise RuntimeError('full candidate frame semantic audit failed before selection')
 frame_hash=digest(candidates);selection_by_cell=select_candidates({cell:tuple(r['variant_id'] for r in records) for cell,records in grouped.items()});selected=sorted(x for values in selection_by_cell.values() for x in values);all_ids={r['variant_id'] for r in candidates};unselected=sorted(all_ids-set(selected));by_id={r['variant_id']:r for r in candidates};audit=aggregate_audit(candidates,development,selected,frame_hash)
 frame={'experiment':'journal_j1_causal_partner_belief','stage':'semantic_candidate_frame_frozen','frame_frozen_before_behavior':True,'candidate_count':360,'cells':18,'candidates_per_cell':20,'behavioral_outcomes_used':False,'icaart_instances_reused':False,'candidate_frame_sha256':frame_hash,'candidates':candidates}
 selection={'candidate_frame_sha256':frame_hash,'selection_seed_literal':SELECTION_SEED_LITERAL,'selection_seed_integer':SELECTION_SEED,'selection_method':'independent_stratified_without_replacement_10_of_20','canonical_input_order_rule':'ascending_lexicographic_variant_id_within_each_archetype_x_difficulty_cell','selected_count':len(selected),'unselected_count':len(unselected),'selected_by_cell':{f'{a}|{d}':list(selection_by_cell[a,d]) for a,d in sorted(selection_by_cell)},'selected_variant_ids':selected,'unselected_variant_ids':unselected,'selected_variant_semantic_hashes':{x:by_id[x]['semantic_signature_sha256'] for x in selected},'selection_before_behavior':True,'selection_uses_behavioral_outcomes':False,'valid_only_after_complete_frame_audit':audit['passed']}
 development_artifact={'experiment':'journal_j1_causal_partner_belief','stage':'development_semantic_scenarios','development_only':True,'confirmatory_eligible':False,'development_count':18,'development_confirmatory_overlap':0,'scenarios':development};return frame,selection,development_artifact,audit
def generate(out=ROOT/'btom_v2'):
 frame,selection,development,audit=build_artifacts();payloads=dict(zip(OUTPUTS[:4],(frame,selection,development,audit)))
 for name,value in payloads.items():(out/name).write_text(json.dumps(value,indent=2,sort_keys=True)+'\n')
 with (out/OUTPUTS[4]).open('w',newline='') as handle:
  fields=('cell','candidate_count','selected_count','unselected_count','development_count','passed');writer=csv.DictWriter(handle,fieldnames=fields,lineterminator='\n');writer.writeheader()
  for cell in sorted(audit['candidate_cell_counts']):writer.writerow({'cell':cell,'candidate_count':audit['candidate_cell_counts'][cell],'selected_count':audit['selected_cell_counts'][cell],'unselected_count':audit['unselected_cell_counts'][cell],'development_count':1,'passed':audit['passed']})
def main():
 p=argparse.ArgumentParser();p.add_argument('--output-dir',type=Path,default=ROOT/'btom_v2');generate(p.parse_args().output_dir)
if __name__=='__main__':main()
